### ISSUE TITLE
Implementation for object moving/swapping and multi-subject composition

### ISSUE THREAD

**Issue by jwh97nn** [damo-vilab/AnyDoor#2]
The paper references additional features of the model, such as object moving/swapping and multi-subject composition. 
However, only the task of teleporting a single object to a specific location is demonstrated in the pipeline. 
I am curious how the model handles the implementation of other tasks.

**Comment by jwh97nn** [comment]
I have discovered in Section 4.4 the implementation details for object moving/swapping. From what I understand, the process involves the following steps:
1. Utilizing SAM to segment the mask.
2. Employing an inpainting model to fill the masked regions.
3. Following the pipeline (in Fig 2) to teleport the object onto the inpainted image.
For object swapping, I assume the same process is applied to both objects.
As for multi-subject composition, is it done by repeating the process for each individual subject?

**Comment by XavierCHEN34** [comment]
Yes, you are right. 
In fact, we explore many ways to deal with multi-subject composition, including the methods to generate all objects in one pass by constraining the cross-attention in the corresponding box region.  However, this "real one-pass" solution performs not well for "extremely small boxes and scene images with extreme aspect ratios".

 As introduced in Section 4.1  our "Zoom-in strategy" enables us to deal with the mentioned cases.  Concretely, we deal with each box using the "Zoom-in strategy"  and take non-overlapped boxes as a batch for a "pseudo-one-pass" solution.

**Comment by jwh97nn** [comment]
Thank you for your confirm.
As the "Zoom-in strategy" states, the boxes are expanded and cropped, does that mean the input is no longer the original image, but the cropped regions. And after the diffusion process, the generated image is resized back and filled into the cropped region for combination.

**Comment by XavierCHEN34** [comment]
yes

**Comment by jwh97nn** [comment]
Thank you for taking the time to reply.

**Comment by LPengYang** [comment]
> 

Hi, thanks for your excellent work. You mentioned that you have explored the "real one-pass" solution, which generates all objects in one pass by constraining the cross-attention in the corresponding box region. However, in this case, how to deal with the extracted detail maps, since detail maps are concatenated with the features of the decoder of U-Net, its dimension increases under multi-objects. And according to my understanding, for multi-subject, the picked "pseudo-one-pass" solution performs single-subject manupilation one-by-one by using the "Zoom-in strategy" for better ability under extreme aspect ratios?

**Comment by LPengYang** [comment]
> Yes, you are right. In fact, we explore many ways to deal with multi-subject composition, including the methods to generate all objects in one pass by constraining the cross-attention in the corresponding box region. However, this "real one-pass" solution performs not well for "extremely small boxes and scene images with extreme aspect ratios".
> 
> As introduced in Section 4.1 our "Zoom-in strategy" enables us to deal with the mentioned cases. Concretely, we deal with each box using the "Zoom-in strategy" and take non-overlapped boxes as a batch for a "pseudo-one-pass" solution.

Hi, thanks for your excellent work. 
You mentioned that you have explored the "real one-pass" solution, which generates all objects in one pass by constraining the cross-attention in the corresponding box region. However, in this case, how to deal with the extracted detail maps, since detail maps are concatenated with the features of the decoder of U-Net, its dimension increases under multi-subject. 
And according to my understanding, for multi-subject, the picked "pseudo-one-pass" solution performs single-subject manupilation one-by-one by using the "Zoom-in strategy" for better ability under extreme aspect ratios?
